[package]
name = "bitty-js-builder"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
itertools = "0.14.0"
minijinja = { version = "2.9.0", features = ["custom_syntax", "loader"] }
serde = {version = "1.0.219", features = ["derive"] }
syntect = { version = "5.2.0"}
walkdir = "2"
