#!/bin/bash

# NOTE: Run this from the root of the project 
# (i.e. above the `pre-scripts` dir)
jsdoc content/v/7.0.0-rc2/bitty-7.0.0-rc2.dev.js -X > content/versions/7/0/0-rc2/documentation/jsdoc_output.json
