#!/bin/bash

# NOTE: Run this from the root of the project 
# (i.e. above the `pre-scripts` dir)
jsdoc content/v/7.0.0-rc1/bitty-7.0.0-rc1.dev.js -X > content/versions/7/0/0-rc1/_docs/jsdoc-output.json
